export const APP_SCREEN = {
  UN_AUTHORIZE: 'UN_AUTHORIZE',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',

  AUTHORIZE: 'AUTHORIZE',
  BOTTOM_BAR: 'BOTTOM_BAR',
  DRAWER_BAR: 'DRAWER_BAR',
  HOME: 'HOME',

  SERVERS: {
    STACK: 'ROUTES.SERVERS.STACK',
    HOME: 'ROUTES.SERVERS.HOME',
  },

  NOTIFICATION: {
    STACK: 'ROUTES.NOTIFICATION.STACK',
    HOME: 'ROUTES.NOTIFICATION.HOME',
    DETAIL: 'ROUTES.NOTIFICATION.DETAIL',
  },

  MESSAGES: {
    STACK: 'ROUTES.MESSAGES.STACK',
    HOME: 'ROUTES.MESSAGES.HOME',
  },

  PROFILE: {
    STACK: 'ROUTES.PROFILE.STACK',
    HOME: 'ROUTES.PROFILE.HOME',
  },
  MENU_THREAD: {
    STACK: 'ROUTES.MENU_THREAD.STACK',
    BOTTOM_SHEET: 'ROUTES.MENU_THREAD.BOTTOM_SHEET',
    CREATE_THREAD: 'ROUTES.MENU_THREAD.CREATE_THREAD',
    CREATE_THREAD_FORM_MODAL: 'ROUTES.MENU_THREAD.CREATE_THREAD_FORM_MODAL'
  },
  MENU_CLAN: {
    STACK: 'ROUTES.MENU_CLAN.STACk',
    CREATE_CATEGORY: 'ROUTES.MENU_CLAN.CREATE_CATEGORY'
  }
}
