export const APP_SCREEN = {
  UN_AUTHORIZE: 'UN_AUTHORIZE',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',

  AUTHORIZE: 'AUTHORIZE',
  BOTTOM_BAR: 'BOTTOM_BAR',
  DRAWER_BAR: 'DRAWER_BAR',
  HOME: 'HOME',

  SERVERS: {
    STACK: 'ROUTES.SERVERS.STACK',
    HOME: 'ROUTES.SERVERS.HOME',
  },

  NOTIFICATION: {
    STACK: 'ROUTES.NOTIFICATION.STACK',
    HOME: 'ROUTES.NOTIFICATION.HOME',
    DETAIL: 'ROUTES.NOTIFICATION.DETAIL',
  },

  MESSAGES: {
    STACK: 'ROUTES.MESSAGES.STACK',
    HOME: 'ROUTES.MESSAGES.HOME',
    MESSAGE_DETAIL: 'ROUTES.MESSAGES.MESSAGE_DETAIL',
    NEW_MESSAGE: 'ROUTES.MESSAGES.NEW_MESSAGE',
    NEW_GROUP: 'ROUTES.MESSAGES.NEW_GROUP',
  },

  FRIENDS: {
    STACK: 'ROUTES.FRIENDS.STACK',
    HOME: 'ROUTES.FRIENDS.HOME',
    ADD_FRIEND: 'ROUTES.FRIENDS.ADD_FRIEND',
    REQUEST_FRIEND: 'ROUTES.FRIENDS.REQUEST_FRIEND',
    REQUEST_FRIEND_SETTING: 'ROUTES.FRIENDS.REQUEST_FRIEND_SETTING',
  },

PROFILE: {
    STACK: 'ROUTES.PROFILE.STACK',
    HOME: 'ROUTES.PROFILE.HOME',
  },

  MENU_THREAD: {
    STACK: 'ROUTES.MENU_THREAD.STACK',
    BOTTOM_SHEET: 'ROUTES.MENU_THREAD.BOTTOM_SHEET',
    CREATE_THREAD: 'ROUTES.MENU_THREAD.CREATE_THREAD',
    CREATE_THREAD_FORM_MODAL: 'ROUTES.MENU_THREAD.CREATE_THREAD_FORM_MODAL',
    MUTE_THREAD_DETAIL_CHANNEL: 'ROUTES.MENU_THREAD.MUTE_THREAD_DETAIL_CHANNEL'
  },

  MENU_CLAN: {
    STACK: 'ROUTES.MENU_CLAN.STACk',
    CREATE_CATEGORY: 'ROUTES.MENU_CLAN.CREATE_CATEGORY'
  },

  SETTINGS: {
    STACK: 'ROUTES.SETTINGS.STACK',
    HOME: 'ROUTES.SETTINGS.HOME',
    LANGUAGE: 'ROUTES.SETTINGS.LANGUAGE',
    PROFILE: 'ROUTES.SETTINGS.PROFILE'
  }
}
