export const STORAGE_DATA_CLAN_CHANNEL_CACHE = 'STORAGE_DATA_CLAN_CHANNEL_CACHE';
export const STORAGE_IS_DISABLE_LOAD_BACKGROUND = 'STORAGE_IS_DISABLE_LOAD_BACKGROUND';
export const STORAGE_CHANNEL_CURRENT_CACHE = 'STORAGE_CHANNEL_CURRENT_CACHE';
export const STORAGE_KEY_TEMPORARY_INPUT_MESSAGES = 'STORAGE_KEY_TEMPORARY_INPUT_MESSAGES';
export const STORAGE_KEY_TEMPORARY_ATTACHMENT = 'STORAGE_KEY_TEMPORARY_ATTACHMENT';
export const STORAGE_CLAN_ID = 'STORAGE_CLAN_ID';
export const STORAGE_AGREED_POLICY = 'STORAGE_AGREED_POLICY';
export const STORAGE_DATA_CATEGORY_CHANNEL = 'STORAGE_DATA_CATEGORY_CHANNEL';
export const STORAGE_RECENT_EMOJI = 'STORAGE_RECENT_EMOJI';

export const ActionEmitEvent = {
	SEND_MESSAGE: '@SEND_MESSAGE',
	SHOW_KEYBOARD: '@SHOW_KEYBOARD',
	SHOW_INFO_USER_BOTTOM_SHEET: '@SHOW_INFO_USER_BOTTOM_SHEET',
	SHOW_SKELETON_CHANNEL_MESSAGE: '@SHOW_SKELETON_CHANNEL_MESSAGE',
	CLEAR_TEXT_INPUT: '@CLEAR_TEXT_INPUT',
	ADD_EMOJI_PICKED: '@ADD_EMOJI_PICKED',
	FETCH_MEMBER_CHANNEL_DM: 'FETCH_MEMBER_CHANNEL_DM',
	SCROLL_TO_ACTIVE_CHANNEL: '@SCROLL_TO_ACTIVE_CHANNEL',
	SCROLL_TO_BOTTOM_CHAT: '@SCROLL_TO_BOTTOM_CHAT',
	SCROLL_TO_CHANNEL_ACTIVE: '@SCROLL_TO_CHANNEL_ACTIVE',
	MESSAGE_ID_TO_JUMP: '@MESSAGE_ID_TO_JUMP',
	CHANNEL_ID_ACTIVE: '@CHANNEL_ID_ACTIVE',
	ON_MENTION_USER_MESSAGE_ITEM: '@ON_MENTION_USER_MESSAGE_ITEM',
	ON_CHANNEL_MENTION_MESSAGE_ITEM: '@ON_CHANNEL_MENTION_MESSAGE_ITEM',
	ON_REACTION_MESSAGE_ITEM: '@ON_REACTION_MESSAGE_ITEM',
	ON_SEARCH_DM: '@ON_SEARCH_DM',
	ON_OPEN_IMAGE_DETAIL_MESSAGE_ITEM: '@ON_OPEN_IMAGE_DETAIL_MESSAGE_ITEM',
	ON_MESSAGE_ACTION_MESSAGE_ITEM: '@ON_MESSAGE_ACTION_MESSAGE_ITEM',
	ON_SWITCH_CHANEL: '@ON_SWITCH_CHANEL'
};
