export const STORAGE_KEY_CLAN_CURRENT_CACHE = 'STORAGE_KEY_CLAN_CURRENT_CACHE';
export const STORAGE_IS_FROM_FCM = 'STORAGE_IS_FROM_FCM';
export const STORAGE_CHANNEL_CURRENT_CACHE = 'STORAGE_CHANNEL_CURRENT_CACHE';
export const STORAGE_KEY_TEMPORARY_INPUT_MESSAGES = 'STORAGE_KEY_TEMPORARY_INPUT_MESSAGES';
export const STORAGE_CLAN_ID = 'STORAGE_CLAN_ID';

export const ActionEmitEvent = {
  SEND_MESSAGE: '@SEND_MESSAGE',
  SHOW_KEYBOARD: '@SHOW_KEYBOARD',
  SHOW_INFO_USER_BOTTOM_SHEET: '@SHOW_INFO_USER_BOTTOM_SHEET',
}
