// TODO: move to shared constants
// IMPORTANT: IF YOU CHANGE THIS FILE, YOU MUST ALSO CHANGE FILE `libs/utils/src/lib/bridge/electron/constants.ts`
export const START_NOTIFICATION_SERVICE = 'PUSH_RECEIVER:::START_NOTIFICATION_SERVICE';
export const NOTIFICATION_SERVICE_STARTED = 'PUSH_RECEIVER:::NOTIFICATION_SERVICE_STARTED';
export const NOTIFICATION_SERVICE_ERROR = 'PUSH_RECEIVER:::NOTIFICATION_SERVICE_ERROR';
export const NOTIFICATION_RECEIVED = 'PUSH_RECEIVER:::NOTIFICATION_RECEIVED';
export const FCM_TOKEN_UPDATED = 'PUSH_RECEIVER:::TOKEN_UPDATED';
export const GET_DEVICE_ID = 'APP::GET_DEVICE_ID';
export const SENDER_ID = 'APP::SENDER_ID';
export const NAVIGATE_TO_URL = 'APP::NAVIGATE_TO_URL';
export const SET_BADGE_COUNT = 'APP::SET_BADGE_COUNT';
export const GET_APP_VERSION = 'APP::GET_APP_VERSION';
export const TRIGGER_SHORTCUT = 'APP::TRIGGER_SHORTCUT';
export const ACTIVE_WINDOW = 'APP::ACTIVE_WINDOW';
export const DOWNLOAD_FILE = 'APP::DOWNLOAD_FILE';
