export enum RightClickList {
	COPY_IMAGE = 'Copy Image',
	SAVE_IMAGE = 'Save Image',
	COPY_LINK = 'Copy Link',
	OPEN_LINK = 'Open Link',
	ADD_REACTION = 'Add Reaction',
	REPLY = 'Reply',
	CREATE_THREAD = 'Create Thread',
	COPY_TEXT = 'Copy Text',
	APPS = 'Apps',
	MARK_UNREAD = 'Mark Unread',
	COPY_MESSAGE_LINK = 'Copy Message Link',
	PIN_MESSAGE = 'Pin Message',
	SPEAK_MESSAGE = 'Speak Message',
	EDIT_MESSAGE = 'Edit Message',
	DELETE_MESSAGE = 'Delete Message',
	REMOVE_REACTIONS = 'Remove Reactions',
	REMOVE_ALL_REACTIONS = 'Remove All Reactions',
	REPORT_MESSAGE = 'Report Message',
	VIEW_REACTIONS = 'View Reactions',
	FORWARD_MESSAGE = 'Forward Message',
}

export enum RightClickPos {
	NONE = 'NONE',
	IMAGE_VIEWER = 'IMAGE_VIEWER',
	MESSAGE_ON_CHANNEL = 'MESSAGE_ON_CHANNEL',
	IMAGE_ON_CHANNEL = 'IMAGE_ON_CHANNEL',
	MORE = 'MORE',
}
